export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';

export const GET_VERIF_REQUEST = 'GET_VERIF_REQUEST';
export const GET_VERIF_SUCCESS = 'GET_VERIF_SUCCESS';
export const GET_VERIF_FAIL = 'GET_VERIF_FAIL';